config/routes.rb
Rails.application.routes.draw do

  get 'chats/index' => 'chats#index', as: :chats
  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end
  
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  patch 'documents/verifySignature' => 'documents#verifySignature', as: :documents_verifySignature
  get 'documents/sign' => 'documents#sign', as: :documents_sign
  patch 'documents/document_user_upload' => 'documents#document_user_upload', as: :document_user_upload
  get 'documents/allshared' => 'documents#allshared', as: :documents_shared

  authenticate :user do
  	root to: 'documents#index', as: :authenticated_root
  end

  get 'signatures/new' => 'signatures#new', as: :signatures_new
  get 'signatures/download' => 'signatures#download', as: :signatures_download

  resources :documents
  resources :signatures, only: [:create, :new]

  root to: 'documents#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_sidebar.html.erb
<nav id="sidebar">
		<div class="sidebar-header">
			<h3>¿Qué puedo hacer?</h3>
		</div>
		<ul class="list-unstyled components">
			<li class="active">
				<%= link_to('Inicio', documents_path) %>
			</li>
			<li>
				<%= link_to('Documentos compartidos', documents_shared_path) %>
			</li>
			<% if current_user.try(:admin?) %>
			<li>
				<%= link_to('Administrar página', rails_admin_path) %>
			</li>
			<% end %>
			<% if current_user.try(:coordinador?) %>
			<li>
				<%= link_to 'Subir documento', new_document_path %>
			</li>
			<% end %>
			<li>
				<a href="#">Firmar documento</a>
			</li>
			<li>
				<%= link_to(current_user.nombre, edit_user_registration_path) %>
			</li>
		</ul>
	</nav>
	<div id="content">
		<div class="container">
			<div class="row">
				<div class="col-4">
					<button type="button" id="sidebarCollapse" class="btn btn-info">
						<i class="fas fa-aling-left"></i>
						<span>Menú</span>
					</button>
				</div>
				<div class="col-4">
					<a class="btn btn-danger" role="button" href=<%=destroy_user_session_path %>> Cerrar sesión
					</a>
				</div>
			</div>
        <br/>
        <script type="text/javascript">
		
		$(document).ready(function () {
			$('#sidebarCollapse').on('click', function () {
				$('#sidebar').toggleClass('active');
			});
		});
	</script>
        </div>
        