config/routes.rb
Rails.application.routes.draw do

  get 'chats/index' => 'chats#index', as: :chats
  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end
  
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  patch 'documents/verifySignature' => 'documents#verifySignature', as: :documents_verifySignature
  get 'documents/sign' => 'documents#sign', as: :documents_sign
  patch 'documents/document_user_upload' => 'documents#document_user_upload', as: :document_user_upload
  get 'documents/allshared' => 'documents#allshared', as: :documents_shared

  authenticate :user do
  	root to: 'documents#index', as: :authenticated_root
  end

  get 'signatures/new' => 'signatures#new', as: :signatures_new
  get 'signatures/download' => 'signatures#download', as: :signatures_download

  resources :documents
  resources :signatures, only: [:create, :new]

  root to: 'documents#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
    def index
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages).find(session[:conversations])
  end
end

app/views/chats/index.html.erb
<%= stylesheet_link_tag "chats" %>
<h1>Chat</h1>
<div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Lista de usuarios</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
            <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>