config/routes.rb
Rails.application.routes.draw do

  get 'chats/index' => 'chats#index', as: :chats
  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end
  
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  patch 'documents/verifySignature' => 'documents#verifySignature', as: :documents_verifySignature
  get 'documents/sign' => 'documents#sign', as: :documents_sign
  patch 'documents/document_user_upload' => 'documents#document_user_upload', as: :document_user_upload
  get 'documents/allshared' => 'documents#allshared', as: :documents_shared

  authenticate :user do
  	root to: 'documents#index', as: :authenticated_root
  end

  get 'signatures/new' => 'signatures#new', as: :signatures_new
  get 'signatures/download' => 'signatures#download', as: :signatures_download

  resources :documents
  resources :signatures, only: [:create, :new]

  root to: 'documents#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
	has_many :signatures
	belongs_to :user
	has_many :collaborators
	has_one_attached :file 
	has_one :documentHash

	validates :nombre, presence: {message: ": El nombre del documento es obligatorio"}, length: {maximum: 255, too_long: "El número de caracteres máximo es de 255"}
	validates :descripcion, presence: {message: ": La descripción es obligatoria"}, on: :create
	validates :file, attached: true, content_type: {in: 'application/pdf', message: 'solo puedes subir pdf'}

	attr_accessor :privateKey
  	attr_accessor :password

	after_save :save_user

	def users=(value)
    	@users = value
  	end

	private 
	def save_user
    	begin
    	@users.each do |user_id|
      		Collaborator.create(user_id: user_id, document_id: self.id)
    	end
    	rescue
      		end
	  end
	  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	require 'openssl'
	require 'tempfile'
	require 'origami'

	def index
		@documents = Document.where(user_id: current_user.id)
	end
	def show
		@document = Document.find(params[:id])
	end
	def new
		@document = Document.new
	end
	def allshared
    	@documents = Document.where(id: Collaborator.select('document_id').where(user_id: current_user.id))
  	end
	def edit
		@document = Document.find(params[:id])
	end
	def create
		@document = Document.new(document_params)
		@document.user_id = current_user.id
		if @document.save
			flash[:notice] = "¡Documento creado!"
			redirect_to documents_path
		else 
			render 'new'	
		end
	end

	def update
		@document = Document.find(params[:id])
		if @document.update(document_reduce_params)
			flash[:notice] = "¡Documento actualizado!"
			redirect_to @document
		end
	end

	def document_user_upload
    	@document = Document.find params[:documentid]
    	@document.users = params[:users]
		@document.save
		flash[:notice] = "¡Documento compartido!"
    	redirect_to documents_path
	  end

	def sign
		@document = Document.find(params[:id])
	end

	def verifySignature

		@document = Document.find(params[:documentid])
		@newDocument = Document.new(document_sign_params)
		@newDocument.nombre = @document.nombre + '_firmadoPor_' + current_user.nombre
		@newDocument.descripcion = @document.descripcion
		
		archivo = File.read(@newDocument.privateKey.tempfile.path)
		#Creación de la llave con base en la llave privada
		begin
			puts "PASO"
			key = OpenSSL::PKey::RSA.new archivo, @newDocument.password
		rescue Exception => e
			puts "NO PASO"
			redirect_to documents_sign_path(id: @document.id), alert: "Contraseña incorrecta"
		end

		digest = OpenSSL::Digest::SHA256.new

		path = Tempfile.new(['uploaded', 'pdf'], Rails.root.to_s + '/tmp/')
		File.open(path, 'wb') do |file|
			file.write(@document.file.download)
		end

		document = File.open(path)

		newSignature = key.sign digest, document.path

		tmpPath = Tempfile.new(['public_digest', '.pdf'], Rails.root.to_s + '/tmp/')
		Prawn::Document.generate(tmpPath) do
			font "Times-Roman"
			text "public key: + #{key.public_key.to_s}", :align => :center
			text "digest: + #{digest.to_s}", :align => :center
		end

		#COMBINAR PDF DE FIRMA CON EL ORIGINAL
		pdf = CombinePDF.new
		pdf << CombinePDF.load(document.path)
		pdf << CombinePDF.load(tmpPath.path)
		finalDoc = Tempfile.new(['signed', '.pdf'], Rails.root.to_s + '/tmp/')
		pdf.save(finalDoc.path)

		certificate = generate_certificate(key)
		pdf_certified = Origami::PDF.read finalDoc.path
		pdf_page = pdf_certified.get_page(1)
		rectangle = Origami::Annotation::Widget::Signature.new
		rectangle.Rect = Origami::Rectangle[:llx => 89.0, :lly => 386.0,:urx =>190.0, :ury => 353.0]

		#AÑADIR LA FIRMA AL RECTANGULO CREADO
		pdf_page.add_annotation(rectangle)
		pdf_certified.sign(certificate, key, 
				:method => 'adbe.pkcs7.sha1',
				:annotation => rectangle,
				:location => 'México',
				:contact => current_user.email,
				:reason => "firma",
				:issuer => current_user.nombre)

		final_certified = Tempfile.new(['certified', '.pdf'], Rails.root.to_s + '/tmp/')
		pdf_certified.save(final_certified.path)

		@newDocument.file.attach(io: File.open(final_certified.path),
								filename: 'signed' + @newDocument.id.to_s + '.pdf',
								content_type: 'application/pdf')
		

		@newDocument.user_id = current_user.id
		puts "GUARDANDO COLABORADOR"
		users = [@document.user_id]
		@newDocument.users = users
		@newDocument.signed = true
		@newDocument.save

		flash[:notice] = "¡Documento firmado!"
		redirect_to @newDocument 
	end

	def generate_certificate(key)
		user = User.find(current_user.id)
		name = OpenSSL::X509::Name.new [['CN', "#{user.nombre}"], ['DC', 'UV']]
		certificate = OpenSSL::X509::Certificate.new
		certificate.version = 2
		certificate.serial = 0
		certificate.not_before = Time.now
		certificate.not_after = Time.now + 3600
		certificate.public_key = key.public_key
		certificate.subject = name
		certificate.issuer = name
		certificate
	end

	private
	def document_reduce_params
		params.require(:document).permit(:nombre, :descripcion)
	end
	def document_params
		params.require(:document).permit(:nombre, :file, :descripcion, :id)
	end
	def document_sign_params
		params.require(:document).permit(:privateKey, :password, :documentid)
	end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/allshared.html.erb
<head>
	<div class="jumbotron bg-primary text-center">
		<h1><font color="white">FirmAndando</font></h1>
	</div>
	<%= link_to "Regresar", :back %>
</head>
<center>
	<h2>Documentos compartidos</h2>
</center><br />
<div class="card-columns" id="cards">
    <% @documents.each do |document| %>
	<div class='card bg-light'>
		<div class='card-body text-center'>
			<h4 class='card-title'><%= document.nombre %></h4>
				<p class='card-text'><%= document.created_at %></p>
				<%= link_to 'Ver detalles', document_path(document) %>
		</div>
    </div>
    <% end %>
</div>

app/views/documents/edit.html.erb
<head>
	<div class="jumbotron bg-primary text-center">
		<h1><font color="white">FirmAndando</font></h1>
	</div>
    <%= link_to "Regresar", :back %>
</head>
<div class="border-form-div-extra">
	<h4>Compartir documento</h4>
	<%= form_with model: @document, local: true do |form| %>
	<h6><%= @document.nombre %></h6>
	<p>Ingresa el correo del colaborador:</p>
	<input type="email" id="email" class="form-control validate" required placeholder="Correo electrónico">
	<br><br>
	<button type="button" id="addEmail" class="btn btn-primary">Agregar usuario</button>
	<br><br>
	<ul class="list-group" id="listEmails">
		
	</ul><br><br>
	<%= form.submit "Cambiar",:class=>'btn btn-primary' %>
	<% end %>

	<script type="text/javascript">
		
		$(document).ready(function () {
			$('#addEmail').on('click', function () {
				
			});
		});
	</script>
</div>			

app/views/documents/index.html.erb
<div class="wrapper">
	<nav id="sidebar">
		<div class="sidebar-header">
			<h3>¿Qué puedo hacer?</h3>
		</div>
		<ul class="list-unstyled components">
			
			<% if current_user.image.attached? %>
			<div style="width:200px; height:auto" class="text-center">
				<%= image_tag(current_user.image, style:'width:100%')%>
			</div>
			<br>
			<% end %>
			<% if current_user.try(:admin?) %>
			<li>
				<%= link_to('Administrar página', rails_admin_path) %>
			</li>
			<% end %>
			<% if current_user.try(:coordinador?) %>
			<li class="active">
				<%= link_to('Mis documentos', documents_path) %>
			</li>
			<li>
				<%= link_to 'Subir documento', new_document_path %>
			</li>
			<% end %>
			<li>
				<%= link_to('Documentos compartidos', documents_shared_path) %>
			</li>
			<li>
				<%= link_to 'Chat', chats_path %>
			</li>
			<li>
				<%= link_to(current_user.nombre, edit_user_registration_path) %>
			</li>
		</ul>
	</nav>
	<div id="content">
		<div class="container">
			<div class="row">
				<div class="col-4">
					<button type="button" id="sidebarCollapse" class="btn btn-info">
						<i class="fas fa-aling-left"></i>
						<span>Menú</span>
					</button>
				</div>
				<div class="col-4">
					<a class="btn btn-danger" role="button" href=<%=destroy_user_session_path %>> Cerrar sesión
					</a>
				</div>
				<% if !(current_user.generatedKeys) %>
				<div class="col-4">
					<a class="btn btn-warning" role="button" href=<%=signatures_new_path %>> Generar llaves</a>
				</div>
				<% end %>
			</div>
		<br/>
		
		<center>
			<h2>Documentos</h2>
		</center><br />
		<div class="card-columns" id="cards">
			<% @documents.each do |document| %>
			<div class='card bg-light'>
				<div class='card-body text-center'>
					<h4 class='card-title'><%= document.nombre %></h4>
					<p class='card-text'><%= document.created_at %></p>
					<%= link_to 'Ver detalles', document_path(document) %>
				</div>
			</div>
			<% end %>
		</div>
	</div>
	
	<script type="text/javascript">
		$(document).ready(function () {
			$('#sidebarCollapse').on('click', function () {
				$('#sidebar').toggleClass('active');
			});
		});
	</script>
</div>

app/views/documents/new.html.erb
<div class="jumbotron bg-info text-center">
  <h1><font color="white">FirmAndando</font></h1>
</div>

<% @document.errors.full_messages.each do |msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <p><%= msg %></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button> 
      </div>
<% end %>

<div class="border-form-div-extra">
  <h2>Subir documento</h2>
  <br />
  <%= form_with model: @document, local: true do |form| %>
  <p>
    <%= form.label :Nombre %><br>
    <%= form.text_field :nombre, :class=>'form-control'%>
  </p>
  <p> 
    <%= form.label :"Archivo (PDF)" %><br>
    <%= form.file_field :file, accept: 'application/pdf' %>
  </p>

  <p>
    <%= form.label :Descripción %><br>
    <%= form.text_area :descripcion, :class=>'form-control'%>
  </p>

  <p>
    <%= form.submit "Registrar",:class=>'btn btn-primary' %>
  </p>
  <% end %>
  <p>
    <%= link_to "Regresar", :back %>
  </p>
</div>

app/views/documents/show.html.erb
<head>
	<div class="jumbotron bg-primary text-center">
		<h1><font color="white">FirmAndando</font></h1>
	</div>
	<%= link_to "Regresar", :back %>
</head>
<body>
	<div class="modal fade" id="editarDocumento" tabindex="-1" role="dialog" aria-labelledby="tituloModal" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header text-center">
					<h5 class="modal-title" id="tituloModal">Descripción</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="md-form mb-5">
					<%= form_with model: @document, local: true do |form| %>
					<%= form.label :Nombre %><br>
    				<%= form.text_field(:nombre, :value => @document.nombre, :class=>'form-control')%><br>
					<%= form.label :Descripción %><br>
    				<%= form.text_area(:descripcion, :value => @document.descripcion, :class=>'form-control') %>
    				</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
					<%= form.submit "Cambiar",:class=>'btn btn-primary' %>
					<% end %>
				</div>
			</div>
		</div>
	</div>

	<div class="modal fade" id="compartirDocumento" tabindex="-1" role="dialog" aria-labelledby="tituloModal" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header text-center">
					<h5 class="modal-title" id="tituloModal">Descripción</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="md-form mb-5">
						<% document_user(@document.id) -%>
						<% if @users.size > 1 %>
							<div>
								<%= form_for @document, url: document_user_upload_path do |f| %>
									<div class="field">
										<%= f.label "Profesores:" %>
										<% @users.each do |user| %>
											<% if user.id != current_user.id %>
												<div class="field">
                              						<%= check_box_tag "users[]", user.id %> <%= user.nombre %>
                            					</div>
											<% end %>
										<% end %>
									</div>
									<%= hidden_field_tag(:documentid, @document.id) %>
                      				<%= f.submit 'Compartir', id: "boton-compartir", class: "btn btn-default"%>
								<%end %>
							</div>
						<% else %>
						<div class="field">
                    		<label>Ya compartiste el documento con todos los usuarios registrados.</label>
                  		</div>
						<% end %>
    				</div>
				</div>
				<div class="modal-footer">

				</div>
			</div>
		</div>
	</div>

<div class="border-form-div-extra">
	<h2>Detalles</h2>
	<p>
		<strong>Nombre:</strong>
		<%= @document.nombre %>
	</p>
	<p>
		<strong>Descripción:</strong>
		<%= @document.descripcion %>
	</p>

	<h5>Opciones</h5><br>
	<%= link_to 'Abrir documento', @document.file %>
	</br><br>
	<%= link_to 'Descargar', @document.file, download: '' %>
	<% unless @document.user_id != current_user.id %>
		<br><br>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editarDocumento">Editar</button>

	<% end %>

	<% if @document.user_id != current_user.id && !@document.signed %>
		<br><br>
		<%= link_to('Firmar documento', documents_sign_path(id: @document.id))%>
	<% end %>

	<% if @document.signed %>
		<br><br>
		<strong>Documento firmado</strong>
	<% end %>

	<% if @document.user_id == current_user.id && current_user.coordinador %>
		<br><br>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#compartirDocumento">Compartir documento</button>
	<% end %>
</div>

<div class="embed-responsive embed-responsive-16by9">
	<iframe class="embed-responsive-item" src=<%= url_for(@document.file) %> allowfullscreen></iframe>
</div>

</body>

app/views/documents/sign.html.erb
<div class="jumbotron bg-info text-center">
  <h1><font color="white">FirmAndando</font></h1>
</div>
<div class="border-form-div-extra">
    <h5 class="text-center">Firmar documento</h5>
    <%= form_for @document, url: documents_verifySignature_path do |f| %>

        <div class="field">
        <br />
            <%= f.label :value, value: "Sube el archivo con tu llave primaria" %><br />
            <%= f.file_field :privateKey, accept:'.pem',:required => true, :class=>'form-control-file' %>
        </div>
        <br />

        <div class="field">
            <%= f.label :value, value: "Introduce tu contraseña" %>
            <%= f.password_field :password, placeholder: "Contraseña", :required => true, :class=>'form-control' %>
        </div>
        <br />
        <%= hidden_field_tag(:documentid, @document.id) %>
        <div class="actions">
        </br>
            <%= f.submit "Firmar documento", :class=>'btn btn-primary' %>
        </div>
    <% end %>
    </br>
    <%= link_to "Regresar", :back %>
  
</div>